### ISSUE TITLE
commonjs instead of requirejs?

### ISSUE THREAD

**Issue by mgcam** [wtsi-npg/bcviz#20]
Both are used to create encapsulated modules. The latter does asynchronous loading and works only in a browser. The former loads synchronously and works also under nodejs. The js files have to be combined in right order into a single minimised file. In practice in production js is concatenated into a single js, so not much difference. Being able to test and run bcviz under nodejs within a command line utility is attractive.

**Comment by jenniferliddle** [comment]
On 14/01/15 19:06, mgcam wrote:
>
> The js files have to be combined in right order into a single
> minimised file.
>

No they don't. This is an optimisation that we may want to look at, at
some stage, but it certainly isn't compulsory.

> Being able to test and run bcviz under nodejs within a command line
> utility is attractive.
>

We can already test and run bcviz on the command line. It's unclear what
advantage running under nodejs will give us.

There may be advantages to using CommonJS over requirejs, and it's
certainly worth spending a little time looking at the two.



-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by mgcam** [comment]
Currently can do CL under a headless browser. If true CL might give an easy option to generate images - might be attractive to researches; also will be possible to include into nodejs CL pipelines.
